[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown', 'mkd']
hook_add = '''
let g:table_mode_corner = '|'
'''

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''

[[plugins]]
repo = 'preservim/nerdtree'
on_cmd = [
    'NERDTree'
]
hook_add = '''
let g:NERDTreeQuitOnOpen=1
let g:NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
on_source = ['needtree']

[[plugins]]
repo = 'kana/vim-smartinput'
on_i=1

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']

